enum Industry {
  SOFTWARE,
  HARDWARE,
  TELECOMMUNICATIONEQUIPMENT,
  TELECOMMUNICATION,
  HEALTHCAREPROVIDER,
  MEDICALEQUIPMENT,
  PHARMA,
  BANK,
  FINANCE,
  INVESTMENT,
  MORTGAGE,
  CLOSEDENDINVESTMENT,
  OPENENDINVESTMENT,
  LIFEINSURANCE,
  INSURANCE,
  REALESTATESERVICE,
  REALESTATEINVESTMENT,
  AUTOMOBILE,
  CONSUMERSERVICE,
  HOUSEHOLDGOODS,
  LEISUREGOODS,
  PERSONALGOODS,
  MEDIA,
  RETAIL,
  TRAVEL,
  BEVERAGE,
  FOOD,
  TABACCO,
  PERSONALCARE,
  CONSTRUCTION,
  AEROSPACE,
  ELECTRONIC,
  GENERALINDUSTRY,
  ENGINEERING,
  INDUSTRALSUPPORT,
  INDUSTRIALTRANSPORT,
  INDUSTRIALMATERIALS,
  INDUSTRIALMINING,
  CHEMICALS,
  OILGASCOAL,
  ALTERNATEENERGY,
  ELECTRICITY,
  GASWATER,
  WASTE,
}

class IndustryString {
  static List<String> getIndustryString() {
    List<String> industryStrings;
    return industryStrings = [
      "Software und Computerdienstleistungen",
      "Technologie Hardware und Ausrüstung",
      "Telekommunikationseinrichtungen",
      "Anbieter von Telekommunikationsdiensten",
      "Gesundheitsdienstleister",
      "Medizinische Geräte und Dienstleistungen",
      "Pharmazeutika und Biotechnologie",
      "Bank",
      "Finanz- und Kreditdienstleistungen",
      "Investmentbanking und Brokerage-Dienstleistungen",
      "Hypotheken-Immobilien-Investmentfonds",
      "Geschlossene Beteiligungen",
      "Lebensversicherung",
      "Versicherungen",
      "Immobilieninvestitionen und Dienstleistungen",
      "Immobilien-Investmentfonds",
      "Automobile und Teile",
      "Consumer Services",
      "Haushaltswaren und Wohnungsbau",
      "Freizeitartikel",
      "Persönliche Güter",
      "Medien",
      "Wiederverkäufer",
      "Reisen und Freizeit",
      "Getränke",
      "Lebensmittelproduzent",
      "Tabacco",
      "Körperpflege-, Drogerie- und Lebensmittelläden",
      "Konstruktion und Materialien",
      "Luft- und Raumfahrt und Verteidigung",
      "Elektronische und elektrische Geräte",
      "Allgemeine Industriezweige",
      "Wirtschaftsingenieurwesen",
      "Industrielle Unterstützungsdienste",
      "Industrieller Transport",
      "Industrielle Materialien",
      "Industriemetalle und Bergbau",
      "Chemikalien",
      "Öl, Gas und Kohle",
      "Alternative Energie",
      "Elektrizität",
      "Gas, Wasser und Multi-Utilities",
      "Abfall- und Entsorgungsdienstleistungen"
    ];
  }
}
