pipeline{
    agent any
    tools{
        gradle 'Gradle_7.4.1'
    }

    stages{

        stage('GradleVersion'){
            steps{
                sh 'gradle --version'
            }
        }

        stage('Compile'){
            steps{
                sh 'gradle compileJava'
            }
        }

        stage ('GradleJar'){
            steps{
                sh 'gradle jar'
            }
        }

        stage ('ArchiveArtifacts'){
            steps{
                archiveArtifacts artifacts: 'build/libs/'
            }
        }

        stage ('Test') {
            steps{
                sh 'gradle test'
            }
        }
    }
}
